from Exceptions.Error import Error


class ValueTooLargeError(Error):
    pass
